repos:
  - repo: https://github.com/hhodac/terrasik-park
    rev: "v0.1"             # e.g. "v0.11.2"
    hooks:
      - id: terraform-docs-go
        args: ["ARGS", "TO PASS", "INCLUDING PATH"]  # e.g. ["--output-file", "README.md", "./mymodule/path"]